apiVersion: apps/v1
kind: Deployment
metadata:
  name: project7-backend
  labels: { app: project7-backend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: project7-backend }
  template:
    metadata:
      labels: { app: project7-backend }
    spec:
      containers:
        - name: backend
          image: __BACK_IMAGE__
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
