apiVersion: v1
kind: ConfigMap
metadata:
  name: project7-frontend-nginx
data:
  default.conf: |
    upstream backend_api {
      server project7-backend-svc:3001;  # <-- Service name + port
    }

    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      # React SPA: serve index.html for client routes
      location / {
        try_files $uri /index.html;
      }

      # API proxy (frontend calls /api/...)
      location /api/ {
        proxy_pass http://backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
      }
    }
