apiVersion: apps/v1
kind: Deployment
metadata:
  name: project7-frontend
  labels: { app: project7-frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: project7-frontend }
  template:
    metadata:
      labels: { app: project7-frontend }
    spec:
      containers:
        - name: frontend
          image: ayush3366/project7-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: project7-frontend-nginx
            items:
              - key: default.conf
                path: default.conf
